apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2024-10-29T08:35:10Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "491"
  uid: e3fee066-61ea-4a15-aceb-52e4a42b2e3f
data:
  policy.csv: |
    p, role:readonly, applications, get, */*, allow
    p, role:read-only, applications, list, */*, allow
    g, sharon-role, role:readonly

